# Generated by Django 5.1.4 on 2025-03-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_backend_message_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20)),
                ('patient_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('report_title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('doctor', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='reports/')),
            ],
        ),
    ]
