# Generated by Django 5.1.5 on 2025-03-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_prescription_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
